project:
  type: website

website:
  title: "Emmett Stralka"
  description: "Engineering Student | Microcontrollers & FPGA Design"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: labs.qmd
        text: Labs
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/stremme1
      - icon: linkedin
        href: https://www.linkedin.com/in/emmett-stralka-b41575213/

format:
  html:
    css: styles.css
    toc: false
    toc-depth: 3
    embed-resources: true
    link-external-newwindow: true
    search: true
    theme: 
      - custom.scss
    page-layout: custom
    container: 
      - "div"
      - "class": "quarto-container-centered"
      - "style": "max-width: 1200px; margin: 0 auto; padding: 0 24px; box-sizing: border-box;"
