project:
  type: website

website:
  title: "Emmett Stralka - Engineering Portfolio"
  description: "Harvey Mudd College Engineering Student | Microcontrollers & FPGA Design | Product Management & UX/UI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: labs.qmd
        text: Labs
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/stremme1
      - icon: linkedin
        href: https://www.linkedin.com/in/emmett-stralka-b41575213/

format:
  html:
    css: styles.css
    toc: false
    toc-depth: 3
    embed-resources: true
    link-external-newwindow: true
    search: true
    theme: 
      - custom.scss
    page-layout: custom
    grid:
      sidebar-width: 250px
      margin-width: 0px
      body-width: 1200px
    layout:
      columns:
        - width: 33%
        - width: 67%
      align: start
