project:
  type: website

website:
  title: "Emmett Stralka - Engineering Portfolio"
  description: "Harvey Mudd College Engineering Student | Microcontrollers & FPGA Design | Product Management & UX/UI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs.qmd
        text: Labs
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/stremme1
      - icon: linkedin
        href: https://www.linkedin.com/in/emmett-stralka-b41575213/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    embed-resources: true
    link-external-newwindow: true
    search: true
