project:
  type: website

website:
  title: "E155-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs.qmd
        text: Labs
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
